Update azure-deploy-infra.yml

diff --git a/.github/workflows/azure-deploy-infra.yml b/.github/workflows/azure-deploy-infra.yml
--- a/.github/workflows/azure-deploy-infra.yml
+++ b/.github/workflows/azure-deploy-infra.yml
@@ -67,6 +67,13 @@ jobs:
           echo "mongoimport --uri=\"$cosmos_cs\" --db=\"${{ secrets.COSMOS_NAME }}\" --collection=\"${{ secrets.COSMOS_COLLECTION2_NAME }}\" --file=./sample_data/samplePosts.json --jsonArray" >> ../cosmos_db_data_import.sh
           echo "$cosmos_cs" > ../cosmos_db_connection_string.txt
 
+          acr_login_server=$(terraform output -raw acr_login_server)
+          if [ -z "$acr_login_server" ]; then
+            echo "Error: acr_login_server string is empty!"
+            exit 1
+          fi
+          echo "$acr_login_server" > ../acr_login_server.txt
+        
       - name: Upload Cosmos DB Data Import Script as artifact
         uses: actions/upload-artifact@v4
         with:
@@ -77,8 +84,10 @@ jobs:
       - name: Upload Cosmos DB connection string as artifact
         uses: actions/upload-artifact@v4
         with:
-          name: cosmos-db-connection-string
-          path: cosmos_db_connection_string.txt
+          name: cosmos-db-and-acr-string
+          path: |
+            cosmos_db_connection_string.txt
+            acr_login_server.txt
           
   ImportDataToMongo:
     name: Import Data
@@ -116,7 +125,7 @@ jobs:
       - name: Download Cosmos DB connection string artifact
         uses: actions/download-artifact@v4
         with:
-          name: cosmos-db-connection-string
+          name: cosmos-db-and-acr-string
 
       - name: Edit parameter
         run: |
@@ -156,11 +165,12 @@ jobs:
         with:
           python-version: 3.9
 
-      - name: Build Docker Image for Deploy 
+      - name: Build and Upload Docker Image for Deploy 
         run: |
+          ACR_REGISTRY=$(cat acr_login_server.txt)
           az acr login --name ${{ secrets.ACR_NAME }}
-          docker build -t $REGISTRY/test:${{ github.sha }} .
-          docker push $REGISTRY/test:${{ github.sha }}
+          docker build -t $ACR_REGISTRY/test:${{ github.sha }} .
+          docker push $ACR_REGISTRY/test:${{ github.sha }}
 
       - name: Build Func Packages for Deploy 
         run: |
