Update azure-deploy-infra.yml

diff --git a/.github/workflows/azure-deploy-infra.yml b/.github/workflows/azure-deploy-infra.yml
--- a/.github/workflows/azure-deploy-infra.yml
+++ b/.github/workflows/azure-deploy-infra.yml
@@ -51,8 +51,13 @@ jobs:
           terraform init
           terraform plan -var-file=variables.tfvars
           terraform apply -auto-approve -var-file=variables.tfvars
+          terraform output -json cosmos_db_connection_string
           cosmos_cs=$(terraform output -json cosmos_db_connection_string | jq -r '.value')
-          echo "cosmos_connection_string=$cosmos_cs" >> $GITHUB_OUTPUT
+          if [ -z "$cosmos_cs" ]; then
+            echo "Error: Cosmos DB connection string is empty!"
+            exit 1
+          fi
+          echo "${cosmos_cs}" | gh secret set COSMOS_DB_CONNECTION_STRING --repo $GITHUB_REPOSITORY
 
   ImportDataToMongo:
     name: Import Data
@@ -69,5 +74,5 @@ jobs:
       # Import data using mongoimport
       - name: Import data into MongoDB
         run: |
-          mongoimport --uri=${{ steps.apply_terraform.outputs.cosmos_connection_string }} --db=${{ secrets.COSMOS_DB_NAME }} --collection=${{ secrets.COSMOS_COLLECTION1_NAME }} --file=./sample_data/sampleAds.json --jsonArray
+          mongoimport --uri=${{ secrets.COSMOS_DB_CONNECTION_STRING }} --db=${{ secrets.COSMOS_DB_NAME }} --collection=${{ secrets.COSMOS_COLLECTION1_NAME }} --file=./sample_data/sampleAds.json --jsonArray
 
